### PR TITLE
Update to v4

### PR DESCRIPTION
**Pull request by alexito4**
Hello, 
I've spent some time updating the package to a more recent commit of Raylib, at version 4. 
There is a couple of commented functions because I'm not sure what's the new version of them. 

I wanted to ask, do you have any automated process to do this or is all done manually?

### CODE REVIEW

**Comment by STREGAsGate** [comment]
Nice! This is is looks good. Nope, no automation; all by hand.

Raylib 4 had a lot of changes so it might take a little bit to review everything you've done.
Thanks for putting the time in! Doing it by hand is a pain, but the user experience ends up being way better imo.

**Comment by alexito4** [comment]
I was looking at their parser.h and maybe that could be an improvement to generate this code. I tried to use it to add raygui support and unfortunately seems like the parser doesn't detect the functions 😂

**Comment by conifer-dev** [comment]
As I wrote on Discord regarding this, I don't think changing original Raylib function names 
Is a good idea:
rb_changes

There should be **no reason** to be changing the whole internal structure of Raylib! None of those re-named functions exists in the original Raylib cheatsheet either which will cause a lot of issues to many Raylib beginners on Swift either finding the right functions or be right out frustrated that the Cheatsheet that provides all the information on the website on what function does what does not work with Raylib on Swift.

**Comment by STREGAsGate** [comment]
Yeah, there is no automation that can make a package of the quality I'm aiming for. Swift is too different from C to be able to translate it automatically, and have it be pretty Swift code.

The raylib_swifty.h file contains some compiler attributes that help, but they still need to be added manually.

_RaylibC can be imported directly and is a purely automated Swift translation. But it's a terrible Swift experience. So I wrapped it and translated the bad translations by hand.

**Review by ghost — APPROVED** [review]
Everything looks good.

**Pull request merged**
